import { type NextPage } from "next";
import Head from "next/head";

import LandingPage from "~/components/LandingPage";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>SSG</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </>
  );
};

export default Home;
